language: python
python:
  - "3.5"
sudo: required
services:
  - docker
  - git
  - python
before_script:
  - docker build . -t scidash/neuronunit
  - docker build ./neuronunit/tests -t scidash/neuronunit-tests
script: 
  - docker run -it scidash/neuronunit
  - docker run -it scidash/neuronunit-tests

