language: python
python:
  - "3.5"
sudo: required
services:
  - docker
  - git
  - python
  
before_script:
  - cd neuronunit/neuronunit/software_tests
  - docker build -t neuronunit .
script: 
  - docker run neuronunit python -m scoop nsga3.py'

