language: python
python:
  - "3.5"
sudo: required
services:
  - docker
  - git
  - python
  
before_script:
  - docker pull -a russelljarvis/nunit 

script: 
  
  - docker run russelljarvis/nunit python -m scoop nsga3.py'

