language: python
python:
  - "3.5"
sudo: required
services:
  - docker
  - git
  - python
  
before_script:
  - docker build -t neuronunit .
  - cd software_tests
script: 
  - docker run neuronunit python -m scoop nsga3.py'

