language: python
python:
  - "3.5"
sudo: required
services:
  - docker
  - git
  - python
  
before_script:
  - docker build -t russelljjarvis/neuronunit .

script: 
  
  - docker run russelljjarvis/neuronunit python -m scoop nsga3.py'

