language: python
python:
  - "3.6"
sudo: required
services:
  - docker
  - git
  - python
  
before_script:
  - docker pull russelljarvis/neuronunit
script: 
  - docker run -it russelljarvis/neuronunit /bin/bash cd ../unit_test; ipython -m unittest testNEURONparallel.py

