version: 2
jobs:
  build:
    machine:
      - image: ubuntu-1604:201903-01

    steps:
      - checkout
      - run: bash ../test.sh
  test:
    machine:
      - image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: bash ../test.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
